### ISSUE TITLE
World type being displayed as generator.RTG on More Options screen

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#23] opened 2016-03-26 12:03 UTC
I checked the encoding on the .lang files for RTG, and everything appears to be the same as the working 1.7 versions. I even deleted the 1.9 files and copied across the ones from 1.7, and it's still not working.

@Adaptivity I remember you helped a lot with the encoding issues in the 1.7 version of RTG... any chance you could take a look at the 1.9 versions if you get a spare moment and see if you can spot anything weird going on?

**Comment by Adaptivity** [comment] 2016-03-26 12:32
Encoding seems to be correct. Does this occurs on 1.8.9 version? If not, most likely something broken on Forge side or something in RTG code.

**Comment by srs-bsns** [comment] 2016-03-26 12:53
Damn, I noticed this earlier when I was testing my update for 1.9 and forgot about it. This only affects 1.9, so it's probably occuring because of some refactoring they did recently. [And there's lots more coming.](https://twitter.com/LexManos/status/713081449994276865)

**Comment by srs-bsns** [comment] 2016-03-26 13:59
Hrm.. after doing a quick look, I didn't see anything standing out that would cause this. I didn't know if @whichonespink44 opened this issue for the 0.0.1 release, or from the travis build after my commit, so I thought that maybe the issue was somewhere in my commit, but after checking 0.0.1 the issue is there as well.

The issue has to be in our code, because I just checked the latest version of BoP from 5 hours ago (1970) and it's working fine there.

**Comment by srs-bsns** [comment] 2016-03-27 01:46
Fixed in https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/commit/4d1d2b794fe190c8a2cebf4f012b2163655ab3b6

**Closed by srs-bsns** 2016-03-27 01:46 UTC
Labels: bug
