### ISSUE TITLE
Floating snow

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#18] opened 2016-03-26 00:46 UTC
![2016-03-26_00 44 10](https://cloud.githubusercontent.com/assets/10927161/14057017/258c940c-f2ec-11e5-863e-4bbd60dbd372.png)

**Comment by topisani** [comment] 2016-03-26 09:09
I'm guessing it's a duplicate of #19. Must be a snowHeightCalculator thing

**Comment by topisani** [comment] 2016-03-26 21:50
@whichonespink44 got a seed? for this or #19

**Comment by whichonespink44** [comment] 2016-03-26 22:03
i dont have that exact one anymore, but this one might work: -2788760844838102142

i'll start posting seeds as standard from now on

**Comment by whichonespink44** [comment] 2016-03-26 22:28
Someone just opened and closed an issue with coords and a seed that might also work:

https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/25

**Closed** 2016-03-26 23:57 UTC
Labels: bug, duplicate
