### ISSUE TITLE
crash on mc 1.9 with rogue like dangeon

### ISSUE THREAD

**Issue by Jiraiyah** [Team-RTG/1.9-Realistic-Terrain-Generation#78] opened 2016-04-19 16:05 UTC
here is the NPE error : 

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraftforge.common.BiomeDictionary.getTypesForBiome(BiomeDictionary.java:206)
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:154)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:59)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:138)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:997)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:979)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:175)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96)
	at net.minecraft.world.World.func_72964_e(World.java:294)
	at net.minecraft.world.World.func_175726_f(World.java:289)
	at jiraiyah.villageinfo.events.WorldDataCollector.getSpawnChunks(WorldDataCollector.java:83)
	at jiraiyah.villageinfo.events.WorldDataCollector.worldLoadEvent(WorldDataCollector.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_74_WorldDataCollector_worldLoadEvent_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Jiraiyah** [comment] 2016-04-19 16:09
this is the line in his repo that gives NPE --> https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/Dungeon.java#L154

BiomeDictionary.getTypesForBiome(biome);

returns null when world is being generated using your generator?

**Comment by topisani** [comment] 2016-04-19 16:09
yep, that is an especially weird one. We have had the same issue with the `BiomeDictionary.getTypesForBiome`. Not sure if this is on our, forge or RLDs side

**Comment by Jiraiyah** [comment] 2016-04-19 16:10
well i posted the same crash report on RLDs repo, will wait and see what you guys find out about it

**Comment by VelocityRa** [comment] 2016-04-20 09:58
Hmm, could you try generating a world without structures? It's an option in the Menu where you choose the Realistic world type.

**Comment by Jiraiyah** [comment] 2016-04-20 10:55
I think i found something, take a look : 

[15:23:47] [Server thread/INFO]: Starting integrated minecraft server version 1.9
[15:23:47] [Server thread/INFO]: Generating keypair
[15:23:47] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[15:23:47] [Server thread/INFO] [FML]: Applying holder lookups
[15:23:47] [Server thread/INFO] [FML]: Holder lookups applied
[15:23:47] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@30dd24a5)
[15:23:47] [Server thread/WARN]: Unable to find spawn biome <----------------------------------------------
[15:23:48] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@30dd24a5)
[15:23:58] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@30dd24a5)
[15:23:58] [Server thread/INFO] [FML]: [RTG-INFO] World Seed: -2120863195

**Comment by Jiraiyah** [comment] 2016-04-20 10:55
the only mod in the folder is yours by the way

**Comment by VelocityRa** [comment] 2016-04-20 10:59
I think @topisani should have a look at this, he's the one who's worked on 1.9 the most. The rest of the team is focusing on releasing 1.0 for 1.7.10 right now and *then* we'll move to 1.9.

**Comment by Jiraiyah** [comment] 2016-04-20 12:26
that was the only part of log interesting, happens every time i build a world and that is from the start of log when i build the world

**Comment by Greymerk** [comment] 2016-04-20 20:41
I'm running forge 1.9 1865 with Roguelike Dungeons 1.5.0 and RTG 0.0.5. No crashes. Will probably need someone to give me a seed and location that causes a crash, or some way to force a crash.

I personally can't reproduce. unless just by flying around in creative until i encounter every biome.

**Comment by whichonespink44** [comment] 2016-04-20 20:44
@Jiraiyah Please post the entire log. It contains the world seed and other information that will help us fix this issue faster.

**Comment by Greymerk** [comment] 2016-04-20 22:56
Here's a crash log.

https://gist.github.com/Greymerk/7c85d7af42105711123c90bc9a3e44e7

**Comment by srs-bsns** [comment] 2016-04-20 23:31
Do you know what biome was being looked up when it crashed?

**Comment by Greymerk** [comment] 2016-04-20 23:52
I put the function call inside a try/catch block and got it to print out the coords.

So far i've seen one in a Plains biome and one in a Birch Forest.

**Comment by topisani** [comment] 2016-04-21 00:03
I think this may be an issue with the biome dictionary and biome types. I was getting NPEs when testing for biome types for scatered features in 1.8.9 already i think. Are we certain this is an RTG issue, or could it be forge?

**Comment by Greymerk** [comment] 2016-04-21 00:18
Interestingly there's a call to another function in the BiomeDictionary afterwards which doesn't crash the server for some reason. That suggests to me that the biome is properly registered.

The forest theme dungeon spawns in the forest like it's supposed to. even though the biome function threw a NPE.

https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/settings/SpawnCriteria.java#L124

**Comment by topisani** [comment] 2016-04-21 00:22
yeah its only the biome type that doesnt seem to work correctly. It might be because of us replacing the biomes from other mods with our versions. Maybe it tries to find a type for our version and cant cause thats not registered

**Comment by srs-bsns** [comment] 2016-04-21 00:53
The biomes have to be getting registered with types, otherwise I'd expect we would have heard about it by now.

I'm not sure exatly what's going on here, but it's certainly worth investigating, even if the problem isn't on RTG's side, in order to rule out a bug that could haunt us in the future.

**Comment by Greymerk** [comment] 2016-04-21 00:53
Well as it turns out i can rewrite the code that crashes using the function call that doesn't crash. so that'll fix this crash on my end. However doesn't really resolve the problem. I'm highly suspicious that this is a forge issue.

**Comment by srs-bsns** [comment] 2016-04-21 00:55
>I'm highly suspicious that this is a forge issue.

Yes, especially considering that some of the Biome Dictionary code is relatively new in 1.9

**Comment by Greymerk** [comment] 2016-04-21 01:03
Here's the change i made. I'm just looking around seeing if a crash happens. so far it's been fine.

https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/Dungeon.java#L164

**Comment by srs-bsns** [comment] 2016-04-21 01:09
How come you are using a custom Coord Class and not BlockPos? Or is that just antiquated code that you haven't update to use BlockPos yet? :expressionless:

**Comment by Greymerk** [comment] 2016-04-21 01:20
1. Because i've been burned by relying on mojang abstractions in the past.
2. Because I came up with the idea of using a Coord object long before BlockPos was put in, and i'd have to rewrite a lot of code to change things now
3. Because I can add capabilities to my own Coord class which BlockPos doesn't support. Such as vector subtraction and distance calculations.
4. My dungeon code still has to work for 1.7.10, which absolutely requires that I have my own Coord class, in the absence of a BlockPos anyway.

**Comment by srs-bsns** [comment] 2016-04-21 01:24
@Greymerk, The only thing I can guess that is happening, is that biomes aren't getting registered properly, and when you call for the types, `checkRegistration(biome)` is executed, which, if the biome isn't registered executes `makeBestGuess(biome)`

https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L289-L393

and for some biomes, they end up not having any types set. So when you call for the types, `null` gets returned, and therefore, NPE.

Heh. Fair enough on the BlockPos.

**Comment by srs-bsns** [comment] 2016-04-21 01:26
If if this does end up being a problem on our side with Biome registration, it will most certainly get worked out during our rewrite for 1.9

**Comment by Greymerk** [comment] 2016-04-21 03:18
I wanted to test something, so i wrote a command that allows me to query biome information for a given coord. all tests had both RD and RTG installed.

In a regular world i could query nearby coords and very distant coords and get accurate biome information from them.

However in realistic world gen i could only query nearby (currently loaded chunks) coords.
One thing i tried was going to 0/0 and checking the biome, it was Forest. Then I tped to 2000/2000 and relogged to make sure all the chunks unloaded. Then checked biome for 0/0 and it told me it found forest biome, but the crash happened when it queried the forge biome type list.

So there's something about chunks being unloaded that triggers this crash specifically with your terrain gen active.

**Comment by topisani** [comment] 2016-04-21 06:42
I suspect that means it's some code that changed from 1.7 to 1.8/9 and we didn't notice and update ours accordingly. I'll look into it, but it sounds like biome provider shenanigans

**Comment by Jiraiyah** [comment] 2016-04-21 15:48
sorry to respond late, but today and next day, i am not having access to the pc with the mods installed, the seed i typed is : Jiraiyah
and it would end me up in a snowy biome, never looked into the F3 screen to see what biome i am in, but every where is snow and more snow :D

**Comment by Jiraiyah** [comment] 2016-04-21 16:16
Ok, got the mod on my laptop, no other mod than yours, but the same seed and biom and everything :

[20:33:15] [Client thread/INFO] [FML]: Max texture size: 8192
[20:33:17] [Client thread/INFO]: Created: 1024x512 textures-atlas
[20:33:24] [Client thread/ERROR] [FML]: MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)
[20:34:19] [Server thread/INFO]: Starting integrated minecraft server version 1.9
[20:34:19] [Server thread/INFO]: Generating keypair
[20:34:19] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[20:34:19] [Server thread/INFO] [FML]: Applying holder lookups
[20:34:19] [Server thread/INFO] [FML]: Holder lookups applied
[20:34:20] [Server thread/INFO] [FML]: Loading dimension 0 (Play World Home) (net.minecraft.server.integrated.IntegratedServer@5582b5f6)
[20:34:20] [Server thread/WARN]: Unable to find spawn biome
[20:34:23] [Server thread/INFO] [FML]: Loading dimension 1 (Play World Home) (net.minecraft.server.integrated.IntegratedServer@5582b5f6)
[20:35:20] [Server thread/INFO] [FML]: Loading dimension -1 (Play World Home) (net.minecraft.server.integrated.IntegratedServer@5582b5f6)
[20:35:20] [Server thread/INFO] [FML]: [RTG-INFO] World Seed: -2120863195  <================ actual seed
[20:35:20] [Server thread/INFO]: Preparing start region for level 0
[20:35:22] [Server thread/INFO] [FML]: Unloading dimension -1
[20:35:22] [Server thread/INFO] [FML]: Unloading dimension 1
[20:35:22] [Server thread/INFO]: Changing view distance to 6, from 10
[20:35:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3080ms behind, skipping 61 tick(s)
[20:35:48] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[20:35:48] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[20:35:48] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 13 mods : FML@8.0.99.99,RTG@1.9-0.0.5,Forge@12.16.0.1865,Chameleon@1.9-2.1.3,JEI@3.2.11.186,StorageDrawers@1.9-3.1.6,BetterSprinting@1.1.4a,CodeChickenCore@2.0.1.53,ChickenChunks@2.0.1.26,graves@1.9-b10-universal,mcp@9.19,villageinfo@1.0.0,portablecrafting@1.9-1.0
[20:35:48] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[20:35:48] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[20:35:48] [Server thread/INFO]: Jiraiyah[local:E:5026ce61] logged in with entity id 1867 at (154.5, 82.0, 245.5)
[20:35:48] [Server thread/INFO]: Jiraiyah joined the game
[20:35:49] [Client thread/INFO] [FML]: [RTG-INFO] World Seed: 0 <======================= ???
[20:35:54] [Client thread/INFO] [JEI]: Registered plugin: mezz.jei.plugins.vanilla.VanillaPlugin
[20:35:54] [Client thread/INFO] [JEI]: Registered plugin: com.gr8pefish.portablecrafting.plugins.jei.JEIPlugin
[20:35:54] [Client thread/INFO] [JEI]: Registered plugin: mezz.jei.plugins.jei.JEIInternalPlugin
[20:36:01] [Server thread/INFO]: Saving and pausing game...
[20:36:01] [Server thread/INFO]: Saving chunks for level 'Play World Home'/Overworld

it's Ice Plains biome

**Comment by topisani** [comment] 2016-04-24 11:04
i am closing this since there will be no updates to v1 anymore. the rewrite is coming soon, and im fairly certain that should fix this too

**Comment by VladimirMangos** [comment] 2016-05-09 00:29
I test recently released RTG-1.9-2.0.0-alpha.1.jar and it also crash in same way as old RTG alpha at 1.9

**Comment by srs-bsns** [comment] 2016-05-09 01:11
@VladimirMangos, that has nothing to do with Rogue-like Dungeons, or RTG, it's a PlantMegaPack issue.

**Comment by VladimirMangos** [comment] 2016-05-09 11:08
Oh, I see. Sorry for missreport.

**Comment by MJRamon** [comment] 2016-05-25 19:43
Do we have any progress with this painful problem?

**Comment by VladimirMangos** [comment] 2016-05-25 20:36
Possible problem still exist. It's not crash for me at load but infinity stack at Building terrain
with log

[00:31:27] [Server thread/WARN]: Unable to find spawn biome
and log end with 
[00:32:29] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@*****,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time

http://pastebin.ca/3609796

**Comment by VladimirMangos** [comment] 2016-05-25 20:37
Withput RTG i not have problems with com.mojang.authlib.exceptions.AuthenticationException

**Comment by topisani** [comment] 2016-05-25 20:53
this cannot possibly (ok very slim chance) have anything to do with RTG. we are not touching anything close to authentication. The message you mentioned will happen when you have closed and reopened your game too many times in a short amount of time

**Comment by VladimirMangos** [comment] 2016-05-25 21:06
I open _first_ time minecrasaft for hours and get this error, after I load profile without RTG and load fine. Possible this just timeout error. I think real problem related to RTG in this line:

[00:31:27] [Server thread/WARN]: Unable to find spawn biome

Without RTG I not have this line in logs. Other problems less important and just follow this.

**Comment by topisani** [comment] 2016-05-25 21:10
thats normal. No idea why it happens, but its normal and it means nothing. it wont give you any kind of issues

**Comment by srs-bsns** [comment] 2016-05-25 21:10
That is a common warning that can show up in the log file, but worlds will generally work regardless. As Topisani said, we don't do anything with authentication.

**Comment by topisani** [comment] 2016-05-25 21:11
ooh @srs-bsns you just got ninjad

**Comment by VladimirMangos** [comment] 2016-05-25 21:14
Ok, sorry then for false alarm. Then original crash fixed. Other problem have unclear source.

Can be AuthenticationException related to some thread blocking proccessing com.mojang.authlib.GameProfile code in result long world generation?

**Closed** 2016-05-25 21:18 UTC
Labels: Needs Investigation
